### ISSUE TITLE
Python wrapper: Change of the exposure time

### ISSUE THREAD

**Issue by werefkin** [BaslerTwSupport/Framegrabber#1]
Hi! Is there any way to adjust the exposure time in the Python wrapper? 
The Native C++ code has: `camera.ExposureMode.SetValue(ExposureMode_Timed);`
Something like that missing in the wrapper, which is an essential functionality.
The Python example includes `frameRate = 100` defined, but the variable is unused.

**Comment by wind0952** [comment]
The example uses [Sgc_setIntegerValue](https://github.com/BaslerTwSupport/Framegrabber/blob/990b61f47e9e85a927d42c0261fcbd2ddc2e2a95/python/AcqAPC.py#L291)  function to adjust width & height of camera. 
So you probably can use Sgc_setEnumerationValue to adjust ExposureMode.

**Comment by werefkin** [comment]
> The example uses [Sgc_setIntegerValue](https://github.com/BaslerTwSupport/Framegrabber/blob/990b61f47e9e85a927d42c0261fcbd2ddc2e2a95/python/AcqAPC.py#L291) function to adjust width & height of camera. So you probably can use Sgc_setEnumerationValue to adjust ExposureMode.

Thank you for the response. Would it be feasible to check if it works as I don't have the hardware yet and only consider ordering this framegrabber? the simplest functionality in Python, as setting the exposure time & grabbing raw data, is needed.

**Comment by wind0952** [comment]
Sure. But I need some information for helping your test. 
May I have your contact information? email and company name, then I can left some notes to support egineer from your side.
If is possible then you can send to my mail, elvis.lee@baslerweb.com. If you don't want give it to me here.

**Comment by wind0952** [comment]
![image](https://github.com/BaslerTwSupport/Framegrabber/assets/9546630/f1a465ce-6394-43fc-8653-cb3568751e99)
![image](https://github.com/BaslerTwSupport/Framegrabber/assets/9546630/cb6fd2ef-4dfe-4208-83b9-56ac5f975d60)
